config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }

   root to: "homepage#index"

  resource :profile, only: [:show] do
    resources :planes, module: :profiles
    resources :bookings, only: [:index], module: :profiles
  end

  resources :planes, only: [:index, :show]

  get "/planes/:plane_id/bookings/pending", to: "profiles/bookings#pending", as: "pending"

  patch "/planes/:plane_id/bookings/validate_booking", to: "profiles/bookings#validate_booking", as: "validate"

  resources :bookings, only: [:create, :index], module: :users

  get "/bonus", to: "homepage#bonus", as: "bonus"

  get '*a', :to => 'errors#not_found'
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  belongs_to :user
  has_many :bookings, dependent: :destroy

  # validation user id (should unique and present)
  validates :user_id, presence: true

  # validation description (should be present)
  validates :description, presence: true

  # validation seat (should be present and should >0 and <20)
  validates_numericality_of :seat, :on => :create
  validates :seat, presence: true, inclusion: { in: (1..20).to_a, allow_nil: false }

  # validation aeroclub (should be present)
  validates :aeroclub, presence: true
  validates :address, presence: true

  validates :price, presence: true

  # validation available (par défaut true)
  validates :available, inclusion: { in: [true, false] }


  # first picture
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  # second picture
  has_attached_file :second_picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  # third picture
  has_attached_file :third_picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/


  geocoded_by :address
  # voir l'active record lifecycle
  after_validation :geocode, if: :address_changed?
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  # Skip authentication for this controller
  skip_before_action :authenticate_user!

  def index
    @address = params['user_input_autocomplete_address']
    @range = params['range'].to_i
    @planes=Plane.near(@address, @range)
    # @booking = @pl.planes.build
    @booking = Booking.new

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@planes) do |plane, marker|
      marker.lat plane.latitude
      marker.lng plane.longitude
      marker.picture({
        url: view_context.image_path("logo.svg"),
        width: 100,
        height: 100})
      marker.title plane.price.to_s
    end
  end

  def show
    @plane = Plane.find(params[:id])
    @plane_coordinates = { lat: @plane.latitute, lng: @plane.longitude }
  end

  private

  def plane_params
    params.require(:plane).permit(:description, :aeroclub, :price, :available, :picture, :second_picture, :third_picture, :seat, :user_id)
  end

end

app/controllers/profiles/planes_controller.rb
module Profiles
  class PlanesController < ApplicationController
    before_action :find_user

    def index
      @planes = @user.planes
      @bookings = find_bookings_of_planes
      # Let's DYNAMICALLY build the markers for the view.
      @markers = Gmaps4rails.build_markers(@planes) do |plane, marker|
        marker.lat plane.latitude
        marker.lng plane.longitude
        marker.picture({
          url: view_context.image_path("logo.svg"),
          width: 100,
          height: 100})
        marker.title plane.price.to_s
      end
    end

    def show
      @plane = @user.planes.find(params[:id])
    end

    def new
      @plane = @user.planes.build
      @plane.available = true
    end

    def create
      @plane = @user.planes.build(planes_params_create)
      @plane.available = true
      if @plane.save
        redirect_to profile_plane_path(@plane)
      else
        render :new
      end
    end

    def edit
      @plane = @user.planes.find(params[:id])
      @bookings = @plane.bookings
    end

    def update
      @plane = @user.planes.find(params[:id])
      @bookings = @plane.bookings
      if @plane.update_attributes(planes_params_update)
        redirect_to :action => 'show', :id => @plane.id
      else
        render :action => 'edit'
      end
    end

    def destroy
      @plane = @user.planes.find(params[:id])
      @plane.destroy
      redirect_to profile_planes_path
    end

  private

  def planes_params_create
    params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
  end

  def planes_params_update
    if params['booking'] == nil
      params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
    else
      params.require(:booking).permit(:plane_id, :status)
      params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
    end
  end

  def find_user
    @user = current_user
  end

  def find_bookings_of_planes
    bookings =[]
    @user.planes.each do |plane|
      bookings << plane.bookings
    end
    return bookings
  end

  end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/planes/_book_form.html.erb
<%= simple_form_for(@booking, url:  bookings_path, html: { class: 'form-inline' }) do |f| %>

  <%= f.error_notification %>
  <%= f.input :plane_id, as: :hidden, input_html: { value: plane.id } %>
  <%= f.input :people, label: false, collection: 1..20, prompt: "personnes" %>


  <div class="input-daterange input-group" id="datepicker">
    <input type="text" placeholder="Check in" class="input-sm form-control" name="booking[check_in]" />
    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
    <input type="text"  placeholder="Check out" class="input-sm form-control" name="booking[check_out]" />
  </div>

  <%= f.button :submit, "Réserver", class: "btn btn-success" %>
<% end %>


<%= content_for(:after_js) do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.input-daterange').datepicker({
        format: 'dd-mm-yyyy'
      });
    });
  </script>
<% end %>

app/views/planes/_plane_profile.html.erb
<div class="row">
  <div class="col-sm-3 right">
    <div id="carousel<%= plane.id %>" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <a href="#Modal<%= plane.id %>" data-toggle="modal", data-target="#Modal<%= plane.id %>">
          <%= image_tag plane.picture.url(:medium) %>
          </a>
          <div class="carousel-caption"></div>
        </div>
        <% if plane.second_picture? || plane.third_picture? %>
          <% if plane.second_picture? %>
            <div class="item">
              <a href="#Modal<%= plane.id %>" data-toggle="modal", data-target="#Modal<%= plane.id %>">
                <%= image_tag plane.second_picture.url(:medium) %>
              </a>
            </div>
          <% end %>
          <% if plane.third_picture? %>
            <div class="item">
              <a href="#Modal<%= plane.id %>" data-toggle="modal", data-target="#Modal<%= plane.id %>">
                <%= image_tag plane.third_picture.url(:medium) %>
              </a>
            </div>
          <% end %>
          <a class="right carousel-control" href="#carousel<%= plane.id %>" data-slide="next" onclick="$('#carousel').carousel('next')"></a>
          <a class="left carousel-control" href="#carousel<%= plane.id %>" data-slide="prev" onclick="$('#carousel').carousel('prev')"></a>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <div>
      <ul class="list-inline list-unstyle">
        <li> <%= render 'book_form', booking: @booking, plane: plane %> </li>
      </ul>
    </div>

    <div class="card bg-white">
      <blockquote>
        <p> <%= plane.description.capitalize %></p>
      </blockquote>
    </div>

    <table class="table table-striped">
      <tr>
        <td>Aeroclub de base</td>
        <td><%= plane.aeroclub %></td>
      </tr>
      <tr>
        <td>Aérodrome</td>
        <td><%= plane.address %></td>
      </tr>
      <tr>
        <td>Nombre de sièges</td>
        <td>
          <% plane.seat.times do %>
            <i class="fa fa-male"></i>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Prix de réservation (indicatif)</td>
        <td><%= plane.price %> <i class="fa fa-eur"></i> </td>
      </tr>
      <tr>
        <td>Avion enregistré depuis</td>
        <td><%= plane.created_at.strftime("%d %B %Y") %></td>
      </tr>
      <tr>
        <td>Dernière mise à jour de l'annonce</td>
        <td><%= plane.updated_at.strftime("%d %B %Y") %></td>
      </tr>
    </table>

      <!-- description -->
      <!-- seats -->
      <!-- picture -->
      <!-- aeroclub -->
      <!-- price -->
  </div>
</div>


<div class="modal fade" id="Modal<%= plane.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="">
      <div class="modal-body">
        <div id="big-carousel<%= plane.id %>" class="carousel slide">
          <div class="carousel-inner">
            <div class="item active">

              <%= image_tag plane.picture, width: "570px"  %>

            <div class="carousel-caption"></div>
            </div>
            <% if plane.second_picture? || plane.third_picture? %>
              <% if plane.second_picture? %>
                <div class="item">

                  <%= image_tag plane.second_picture, width: "570px" %>

                </div>
              <% end %>
              <% if plane.third_picture? %>
                <div class="item">

                  <%= image_tag plane.third_picture, width: "570px" %>

                </div>
              <% end %>
              <a class="right carousel-control" href="#big-carousel<%= plane.id %>" data-slide="next" onclick="$('#big-carousel').carousel('next')"></a>
              <a class="left carousel-control" href="#big-carousel<%= plane.id %>" data-slide="prev" onclick="$('#big-carousel').carousel('prev')"></a>
            <% end %>
          </div>
        </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/planes/index.html.erb
<div class="container padded">

  <div id="map" style="width: 100%; height: 400px;"></div>

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          <% if @markers.count == 1 %>
            handler.getMap().setZoom(12);
          <% end %>
        });
      })
    <% end %>
  <% end %>
  <div class="list padded">
  <% @planes.each do |plane| %>
    <%= render 'plane_profile', plane: plane, booking: @booking %>
  <% end %>
  </div>
</div>

app/views/planes/show.html.erb
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @flat_coordinates %>;
      alert('Flat coordinates are ' + coord.lat + ', ' + coord.lng);
    });
  <% end %>
<% end %>