config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }

   root to: "homepage#index"

  resource :profile, only: [:show] do
    resources :planes, module: :profiles
    resources :bookings, only: [:index], module: :profiles
  end

  resources :planes, only: [:index, :show]

  get "/planes/:plane_id/bookings/pending", to: "profiles/bookings#pending", as: "pending"

  patch "/planes/:plane_id/bookings/validate_booking", to: "profiles/bookings#validate_booking", as: "validate"

  resources :bookings, only: [:create, :index], module: :users

  get "/bonus", to: "homepage#bonus", as: "bonus"

  get '*a', :to => 'errors#not_found'
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  skip_before_action :authenticate_user!

  def index
    @booking = Booking.new
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/bonus.html.erb
    <div>
      <div class="container">
        <div class="row">
          <h1 class="text-center">PLANE RACE BONUS</h1>
        </div>
        <div class="row text-center">
            <button class="btn btn-danger">Restart</button>
        </div>
        <div class="row text-center">
          <p></p>
          <p>Player 1: appuyer sur q pour avancer</p>
          <p>Player 2: appuyer sur p pour avancer</p>
          <p><p>Si notre projet vous a plu, vous pouvez nous contacter sur contact.planebnb@gmail.com </p></p>
        </div>
      </div>
    </div>


    <hr>
      <table class="racer_table">
        <tr id="player1_race">
          <td class="active"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="final">Arrivée</td>
        </tr>
        <tr id="player2_race">
          <td class="active"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="final">Arrivée</td>
        </tr>
      </table>
    <hr>


<%= content_for(:before_js) do %>
  <%= javascript_include_tag "wagon_race.js" %>
<% end %>

app/views/homepage/index.html.erb
<div class = "bg-black" id = "video">
  <video autoplay="autoplay" muted="muted" width="100%" preload="auto" loop>
    <source src="http://mazwai.com/system/posts/videos/000/000/121/original/jedd-goble--big_shorts_pro_velocity.mp4?1412888128#t=0,9.6" type="video/mp4">
  </video>
</div>

<div class="text-center height-none search">

      <h1>Cherchez un avion partout en France ! </h1>
      <h3>Planebnb, le leader de la location d'avion entre particuliers </h3>
      <br><br>
      <%= form_tag planes_path, method: :get , class: 'form-inline' do %>
        <%= text_field_tag :user_input_autocomplete_address, nil, { class: 'form-control'} %>
        <%= select_tag :range, options_for_select((0..1000).step(10).to_a), { class: 'form-control', prompt: "Rayon de recherche?"} %>
        <%= submit_tag "Décollage!", { class: 'btn btn-primary' } %>
      <% end %>
</div>


<div class = "bg-black size_home">
</div>


<%= content_for(:before_js) do %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyCEchjv-lKDE8tKplZsEvpTJQKL1R3Lqn4" %>
  <%= javascript_include_tag "autocomplete.js" %>
<% end %>