config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }

   root to: "homepage#index"

  resource :profile, only: [:show] do
    resources :planes, module: :profiles
    resources :bookings, only: [:index], module: :profiles
  end

  resources :planes, only: [:index, :show]

  get "/planes/:plane_id/bookings/pending", to: "profiles/bookings#pending", as: "pending"

  patch "/planes/:plane_id/bookings/validate_booking", to: "profiles/bookings#validate_booking", as: "validate"

  resources :bookings, only: [:create, :index], module: :users

  get "/bonus", to: "homepage#bonus", as: "bonus"

  get '*a', :to => 'errors#not_found'
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  belongs_to :user
  has_many :bookings, dependent: :destroy

  # validation user id (should unique and present)
  validates :user_id, presence: true

  # validation description (should be present)
  validates :description, presence: true

  # validation seat (should be present and should >0 and <20)
  validates_numericality_of :seat, :on => :create
  validates :seat, presence: true, inclusion: { in: (1..20).to_a, allow_nil: false }

  # validation aeroclub (should be present)
  validates :aeroclub, presence: true
  validates :address, presence: true

  validates :price, presence: true

  # validation available (par défaut true)
  validates :available, inclusion: { in: [true, false] }


  # first picture
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  # second picture
  has_attached_file :second_picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  # third picture
  has_attached_file :third_picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/


  geocoded_by :address
  # voir l'active record lifecycle
  after_validation :geocode, if: :address_changed?
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  # Skip authentication for this controller
  skip_before_action :authenticate_user!

  def index
    @address = params['user_input_autocomplete_address']
    @range = params['range'].to_i
    @planes=Plane.near(@address, @range)
    # @booking = @pl.planes.build
    @booking = Booking.new

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@planes) do |plane, marker|
      marker.lat plane.latitude
      marker.lng plane.longitude
      marker.picture({
        url: view_context.image_path("logo.svg"),
        width: 100,
        height: 100})
      marker.title plane.price.to_s
    end
  end

  def show
    @plane = Plane.find(params[:id])
    @plane_coordinates = { lat: @plane.latitute, lng: @plane.longitude }
  end

  private

  def plane_params
    params.require(:plane).permit(:description, :aeroclub, :price, :available, :picture, :second_picture, :third_picture, :seat, :user_id)
  end

end

app/controllers/profiles/bookings_controller.rb
module Profiles
  class BookingsController < ApplicationController
    before_action :find_user
    # current_user.planes...

    def index
      @bookings = find_bookings
    end

    def pending
      @plane = Plane.find(params[:plane_id])
      @bookings = @plane.bookings
    end

    def validate_booking
      @booking = Booking.find(params["booking"]["id"].to_i)
      if params['status-checkbox'] == "on"
        @booking.status = true
        @booking.save
      else
        @booking.status = false
        @booking.save
      end
      @bookings = find_bookings
      redirect_to pending_path
    end

   private

    def find_user
      @user = current_user
    end

    def booking_params
      params.require(:booking).permit(:status)
    end

    def find_bookings
      bookings =[]
      @user.planes.each do |plane|
        bookings << plane.bookings
      end
      return bookings
    end
  end
end

app/controllers/profiles/planes_controller.rb
module Profiles
  class PlanesController < ApplicationController
    before_action :find_user

    def index
      @planes = @user.planes
      @bookings = find_bookings_of_planes
      # Let's DYNAMICALLY build the markers for the view.
      @markers = Gmaps4rails.build_markers(@planes) do |plane, marker|
        marker.lat plane.latitude
        marker.lng plane.longitude
        marker.picture({
          url: view_context.image_path("logo.svg"),
          width: 100,
          height: 100})
        marker.title plane.price.to_s
      end
    end

    def show
      @plane = @user.planes.find(params[:id])
    end

    def new
      @plane = @user.planes.build
      @plane.available = true
    end

    def create
      @plane = @user.planes.build(planes_params_create)
      @plane.available = true
      if @plane.save
        redirect_to profile_plane_path(@plane)
      else
        render :new
      end
    end

    def edit
      @plane = @user.planes.find(params[:id])
      @bookings = @plane.bookings
    end

    def update
      @plane = @user.planes.find(params[:id])
      @bookings = @plane.bookings
      if @plane.update_attributes(planes_params_update)
        redirect_to :action => 'show', :id => @plane.id
      else
        render :action => 'edit'
      end
    end

    def destroy
      @plane = @user.planes.find(params[:id])
      @plane.destroy
      redirect_to profile_planes_path
    end

  private

  def planes_params_create
    params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
  end

  def planes_params_update
    if params['booking'] == nil
      params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
    else
      params.require(:booking).permit(:plane_id, :status)
      params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
    end
  end

  def find_user
    @user = current_user
  end

  def find_bookings_of_planes
    bookings =[]
    @user.planes.each do |plane|
      bookings << plane.bookings
    end
    return bookings
  end

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_picture(version=nil)
    if current_user.uid
      current_user.picture
    else
      current_user.profile_picture_file_name ? current_user.profile_picture.url(version) : "pilot.svg"
    end
  end

  def profile_picture_navbar(version=nil)
    if current_user.uid
      current_user.picture
    else
      current_user.profile_picture_file_name ? current_user.profile_picture.url(version) : "pilot_navbar.svg"
    end
  end

end

app/views/profiles/planes/_booking_status.html.erb
<% if @bookings != nil && @bookings.flatten.select {|element| element.plane_id == plane.id }.first != nil %>
  <tr>
    <td class="bg-green">
      <strong>
        Demandes de réservation
      </strong>
    </td>
    <td class="bg-green">
      <strong>
        <%= link_to "Voir", pending_path(plane), :class => "btn btn-primary btn-black" %>
      </strong>
    </td>
  </tr>
<% end %>

app/views/profiles/planes/_form.html.erb
<%= simple_form_for(@plane, url: profile_planes_path, html: { multipart: true }) do |f| %>

  <%= f.error_notification %>

  <%= f.input :description, required: true, autofocus: true %>
  <%= f.input :seat, :label => "Places disponibles dans l'avion", collection: 1..20, prompt: "Nombre de places disponibles" %>
  <%= f.input :aeroclub, :label => "Base au sol - Nom de l'aéroclub", required: true %>

  <%= f.input :address, :label => "Adresse de l'aérodrome",required: true, input_html: {id: "user_input_autocomplete_address", placeholder: "Adresse de l'aérodrome de base"} %>

  <%= f.input :city, readonly: true, :label => "Ville", input_html: {id: "locality", placeholder: "ville"} %>

  <%= f.input :admin_area, readonly: true, :label => "Département", input_html: {id: "administrative_area_level_1", placeholder: "département"} %>

  <%= f.input :price, :label => "Prix à la journée (euros)", required: true %>

  <%= f.input :picture, :label => "Photo principale de l'avion", required: true %>

  <%= f.input :second_picture, :label => "Ajoutez une photo supplémentaire", required: false %>

  <%= f.input :third_picture, :label => "Ajoutez une photo supplémentaire", required: false %>

  <%= f.button :submit, "Publier mon annonce", class: "btn btn-success" %>
<% end %>

<%= content_for(:before_js) do %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyCEchjv-lKDE8tKplZsEvpTJQKL1R3Lqn4" %>
  <%= javascript_include_tag "autocomplete.js" %>
<% end %>

app/views/profiles/planes/_plane_booking_list.html.erb
<div class="row">
    <div class="col-sm-2 right">
        <%= image_tag @plane.picture.url(:medium),  class: "img-thumbnail" %>
    </div>
    <div class="col-md-7 col-md-offset-1">

      <table class="table table-striped">
        <%= render 'user_booking' %>
      </table>

    </div>
  </div>

app/views/profiles/planes/_plane_profile.html.erb
<div class="row">
  <div class="col-sm-3 right">
    <div id="carousel<%= plane.id %>" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <a href="#myModal<%= plane.id %>" data-toggle="modal", data-target="#myModal<%= plane.id %>">
          <%= image_tag plane.picture.url(:medium) %>
          </a>
          <div class="carousel-caption"></div>
        </div>
        <% if plane.second_picture? || plane.third_picture? %>
          <% if plane.second_picture? %>
            <div class="item">
              <a href="#myModal<%= plane.id %>" data-toggle="modal", data-target="#myModal<%= plane.id %>">
                <%= image_tag plane.second_picture.url(:medium) %>
              </a>
            </div>
          <% end %>
          <% if plane.third_picture? %>
            <div class="item">
              <a href="#myModal<%= plane.id %>" data-toggle="modal", data-target="#myModal<%= plane.id %>">
                <%= image_tag plane.third_picture.url(:medium) %>
              </a>
            </div>
          <% end %>
          <a class="right carousel-control" href="#carousel<%= plane.id %>" data-slide="next" onclick="$('#carousel').carousel('next')"></a>
          <a class="left carousel-control" href="#carousel<%= plane.id %>" data-slide="prev" onclick="$('#carousel').carousel('prev')"></a>
        <% end %>
      </div>
    </div>
  </div>


  <div class="col-md-7 col-md-offset-1">
    <div>
      <ul class="list-inline list-unstyle">
        <li><%= link_to "Mettre à jour l'annonce", edit_profile_plane_path(plane), class: "btn btn-primary" %></li>
        <li><%= link_to "Supprimer l'annonce", profile_plane_path(plane), class: "btn btn-danger", method: :delete, data: { confirm: "Etes-vous sûr de vouloir supprimer définitivement l'annonce?" } %></li>
      </ul>
    </div>

    <div class="card bg-white">
      <blockquote>
        <p> <%= plane.description %></p>
      </blockquote>
    </div>

    <table class="table table-striped">
      <tr>
        <td>Aeroclub de base</td>
        <td><%= plane.aeroclub %></td>
      </tr>
      <tr>
        <td>Aérodrome</td>
        <td><%= plane.address %></td>
      </tr>
      <tr>
        <td>Nombre de sièges</td>
        <td>
          <% plane.seat.times do %>
            <i class="fa fa-male"></i>
          <% end %>
        </td>
      </tr>
      <%= render 'booking_status', plane: plane %>
      <tr>
        <td>Prix de réservation (indicatif)</td>
        <td><%= plane.price %> <i class="fa fa-eur"></i> </td>
      </tr>
      <tr>
        <td>Avion enregistré depuis</td>
        <td><%= plane.created_at.strftime("%d %B %Y") %></td>
      </tr>
      <tr>
        <td>Dernière mise à jour de l'annonce</td>
        <td><%= plane.updated_at.strftime("%d %B %Y") %></td>
      </tr>
    </table>
  </div>
</div>




<div class="modal fade" id="myModal<%= plane.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="">
      <div class="modal-body">
        <div id="big-carousel<%= plane.id %>" class="carousel slide">
          <div class="carousel-inner">
            <div class="item active">

              <%= image_tag plane.picture, width: "570px"  %>

            <div class="carousel-caption"></div>
            </div>
            <% if plane.second_picture? || plane.third_picture? %>
              <% if plane.second_picture? %>
                <div class="item">

                  <%= image_tag plane.second_picture, width: "570px" %>

                </div>
              <% end %>
              <% if plane.third_picture? %>
                <div class="item">

                  <%= image_tag plane.third_picture, width: "570px" %>

                </div>
              <% end %>
              <a class="right carousel-control" href="#big-carousel<%= plane.id %>" data-slide="next" onclick="$('#big-carousel').carousel('next')"></a>
              <a class="left carousel-control" href="#big-carousel<%= plane.id %>" data-slide="prev" onclick="$('#big-carousel').carousel('prev')"></a>
            <% end %>
          </div>
        </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/profiles/planes/_user_booking.html.erb
<% n = 0 %>
<% @bookings.each do |booking| %>
  <tr>
    <td class = "bg-yellow"><strong>Réservation <%= "#{n + 1}" %> </strong></td>
    <td> <input type="checkbox" name="status-checkbox" checked></td>
  </tr>
  <tr>
    <td>Date de la réservation</td>
    <td><%= booking.created_at %></td>
  </tr>
  <tr>
    <td>Date de début de location</td>
    <td><%= booking.check_in %></td>
  </tr>
  <tr>
    <td>Date de fin de location</td>
    <td><%= booking.check_out %></td>
  </tr>
  <tr>
    <td>Adresse email de l'utilisateur</td>
    <td><%= booking.user.email %></td>
  </tr>
  <tr>
    <td>Lien vers le profil de l'utilisateur</td>
    <td><i class="fa fa-user"></i><%= booking.user.email %></td>
  </tr>
<% end %>

app/views/profiles/planes/edit.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>Mettre à jour l'annonce</h2>

      <%= simple_form_for(@plane, url: profile_plane_path, :method => :patch, html: { multipart: true }) do |f| %>

        <%= f.error_notification %>

        <%= f.input :description, required: true, autofocus: true %>
        <%= f.input :seat, :label => "Places disponibles dans l'avion", collection: 1..20, prompt: "Nombre de places disponibles" %>
        <%= f.input :aeroclub, :label => "Base au sol - Nom de l'aéroclub", required: true %>


        <%= f.input :address, :label => "Adresse de l'aérodrome",required: true, input_html: {id: "user_input_autocomplete_address", placeholder: "Adresse de l'aérodrome de base"} %>

        <%= f.input :city, readonly: true, :label => "Ville", input_html: {id: "locality", placeholder: "ville"} %>

        <%= f.input :admin_area, disabled: true, :label => "Département", input_html: {id: "administrative_area_level_1", placeholder: "département"} %>

        <%= f.input :price, :label => "Prix à la journée (euros)", required: true %>
        <%= f.input :picture, :label => "Photo principale de l'avion", required: true %>

        <%= f.input :second_picture, :label => "Ajoutez une photo supplémentaire", required: false %>

        <%= f.input :third_picture, :label => "Ajoutez une photo supplémentaire", required: false %>

        <%= f.button :submit, "Mettre à jour mon annonce", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>


<%= content_for(:before_js) do %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyCEchjv-lKDE8tKplZsEvpTJQKL1R3Lqn4" %>
  <%= javascript_include_tag "autocomplete.js" %>
<% end %>

app/views/profiles/planes/index.html.erb
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="text-center light-padded">
        <h2>Carte de vos avions enregistrés</h2>
      </div>
      <div id="map" style="width: 100%; height: 400px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).on('ready', function() {
            handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function(){
              markers = handler.addMarkers(<%= raw @markers.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
            });
          })
        <% end %>
      <% end %>
    </div>
  </div>

<div class="container padded">
  <% @planes.each do |plane| %>
    <%= render 'plane_profile', plane: plane %>
    <br>
    <br>
  <% end %>
</div>

app/views/profiles/planes/new.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>Publier une annonce</h2>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/profiles/planes/show.html.erb
<div class="container padded">
  <div>
    <h3> <li><%= link_to "Revenir à mes annonces", profile_planes_path, class: "btn btn-link" %></li></li></h3>
  </div>
  <%= render 'plane_profile', plane: @plane %>
</div>