config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }

   root to: "homepage#index"

  resource :profile, only: [:show] do
    resources :planes, module: :profiles
    resources :bookings, only: [:index], module: :profiles
  end

  resources :planes, only: [:index, :show]

  get "/planes/:plane_id/bookings/pending", to: "profiles/bookings#pending", as: "pending"

  patch "/planes/:plane_id/bookings/validate_booking", to: "profiles/bookings#validate_booking", as: "validate"

  resources :bookings, only: [:create, :index], module: :users

  get "/bonus", to: "homepage#bonus", as: "bonus"

  get '*a', :to => 'errors#not_found'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :plane
  belongs_to :user

  # to do add validation
  validates :user_id, presence: true
  validates :plane_id, presence: true
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates_numericality_of :people, :on => :create
  validates :people, presence: true, inclusion: { in: (1..20).to_a, allow_nil: false }
end

app/controllers/profiles/bookings_controller.rb
module Profiles
  class BookingsController < ApplicationController
    before_action :find_user
    # current_user.planes...

    def index
      @bookings = find_bookings
    end

    def pending
      @plane = Plane.find(params[:plane_id])
      @bookings = @plane.bookings
    end

    def validate_booking
      @booking = Booking.find(params["booking"]["id"].to_i)
      if params['status-checkbox'] == "on"
        @booking.status = true
        @booking.save
      else
        @booking.status = false
        @booking.save
      end
      @bookings = find_bookings
      redirect_to pending_path
    end

   private

    def find_user
      @user = current_user
    end

    def booking_params
      params.require(:booking).permit(:status)
    end

    def find_bookings
      bookings =[]
      @user.planes.each do |plane|
        bookings << plane.bookings
      end
      return bookings
    end
  end
end

app/controllers/profiles/planes_controller.rb
module Profiles
  class PlanesController < ApplicationController
    before_action :find_user

    def index
      @planes = @user.planes
      @bookings = find_bookings_of_planes
      # Let's DYNAMICALLY build the markers for the view.
      @markers = Gmaps4rails.build_markers(@planes) do |plane, marker|
        marker.lat plane.latitude
        marker.lng plane.longitude
        marker.picture({
          url: view_context.image_path("logo.svg"),
          width: 100,
          height: 100})
        marker.title plane.price.to_s
      end
    end

    def show
      @plane = @user.planes.find(params[:id])
    end

    def new
      @plane = @user.planes.build
      @plane.available = true
    end

    def create
      @plane = @user.planes.build(planes_params_create)
      @plane.available = true
      if @plane.save
        redirect_to profile_plane_path(@plane)
      else
        render :new
      end
    end

    def edit
      @plane = @user.planes.find(params[:id])
      @bookings = @plane.bookings
    end

    def update
      @plane = @user.planes.find(params[:id])
      @bookings = @plane.bookings
      if @plane.update_attributes(planes_params_update)
        redirect_to :action => 'show', :id => @plane.id
      else
        render :action => 'edit'
      end
    end

    def destroy
      @plane = @user.planes.find(params[:id])
      @plane.destroy
      redirect_to profile_planes_path
    end

  private

  def planes_params_create
    params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
  end

  def planes_params_update
    if params['booking'] == nil
      params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
    else
      params.require(:booking).permit(:plane_id, :status)
      params.require(:plane).permit(:description, :seat, :aeroclub, :available, :created_at, :updated_at, :price, :picture, :second_picture, :third_picture, :city, :admin_area, :address, :latitude, :longitude)
    end
  end

  def find_user
    @user = current_user
  end

  def find_bookings_of_planes
    bookings =[]
    @user.planes.each do |plane|
      bookings << plane.bookings
    end
    return bookings
  end

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/users/bookings_controller.rb
module Users
  class BookingsController < ApplicationController
    before_action :find_user

    def index
      @bookings = @user.bookings
    end

    def new
      @booking = @user.bookings.build
    end

    def create
      @booking = Booking.new(booking_params)
      @booking.user = current_user
      if @booking.save
        redirect_to bookings_path
      else
        redirect_to planes_path
      end
    end

    private

    def booking_params
      params.require(:booking).permit(:user_id, :plane_id, :people, :check_in, :check_out, :created_at, :updated_at)
    end

    def find_user
       @user = current_user
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_picture(version=nil)
    if current_user.uid
      current_user.picture
    else
      current_user.profile_picture_file_name ? current_user.profile_picture.url(version) : "pilot.svg"
    end
  end

  def profile_picture_navbar(version=nil)
    if current_user.uid
      current_user.picture
    else
      current_user.profile_picture_file_name ? current_user.profile_picture.url(version) : "pilot_navbar.svg"
    end
  end

end

app/views/profiles/bookings/_booking_profile.html.erb
<div class="row">
  <div class="col-sm-2 right">
      <%= image_tag booking.plane.picture.url(:medium),  class: "img-thumbnail" %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <table class="table table-striped">
      <tr>
        <td>Aeroclub de base</td>
        <td><%= booking.plane.aeroclub %></td>
      </tr>
      <tr>
        <td>Nombre de personnes</td>
        <td>
          <% booking.people.times do %>
            <i class="fa fa-male"></i>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Prix de réservation (indicatif)</td>
        <td><%= booking.plane.price %> <i class="fa fa-eur"></i> </td>
      </tr>
      <tr>
        <td>Locataire de l'avion </td>
        <td><%= booking.user.firstname %> <%= booking.user.lastname %></td>
      </tr>
      <tr>
        <td>Date de check in</td>
        <td><%= booking.check_in.strftime("%d %B %Y") %></td>
      </tr>
      <tr>
        <td>Date de check out</td>
        <td><%= booking.check_out.strftime("%d %B %Y") %></td>
      </tr>
      <tr>
          <%= render 'booking_status', booking: booking %>
      </tr>
    </table>
  </div>
</div>

app/views/profiles/bookings/_booking_status.html.erb
<% if booking.status == true %>
  <td class="bg-green">
    <strong>
      Statut de ma réservation
    </strong>
  </td>
  <td class="bg-green">
    <strong>Confirmée !</strong>
  </td>
<% elsif booking.status == false %>
  <td class="bg-red">
    <strong>
      Statut de ma réservation
    </strong>
  </td>
  <td class="bg-red">
    <strong>Refusée</strong>
  </td>
<% else %>
  <td class="bg-yellow">
    <strong>
      Statut de ma réservation
    </strong>
  </td>
  <td class="bg-yellow">
    <strong>En attente...</strong>
  </td>
<% end %>

app/views/profiles/bookings/_user_booking.html.erb
<% n = 0 %>
<% bookings.each do |booking| %>

  <div class="row">

    <div class="col-sm-2 right">
        <% if booking.user.uid %>
          <%= image_tag booking.user.picture.url(:medium),  class: "img-thumbnail" %>
      <% else %>
        <% if booking.user.profile_picture_file_name %>
            <%= image_tag booking.user.profile_picture.url(:medium),  class: "img-thumbnail" %>
          <% else %>
            <%= image_tag "pilot_navbar.svg" %>
          <% end %>
      <% end %>
    </div>

    <div class="col-md-7 col-md-offset-1">
      <table class="table table-striped">
        <tr>
            <td>
              <strong>
                Réservation <%= "#{n += 1}" %>
              </strong>
            </td>
          <td>
            <%= form_for(booking, url:  validate_path, html: { class: 'form-inline' }) do |f| %>

              <input type="checkbox" name="status-checkbox" class="form-control" checked>
               <%= f.hidden_field :id, value: "#{booking.id}" %>
              <input type="submit" value="Valider" class="form-control">
            <% end %>
          </td>
        </tr>
        <tr>
            <%= render 'booking_status', booking: booking %>
        </tr>
        <tr>
          <td>Date de la réservation</td>
          <td><%= booking.created_at %></td>
        </tr>
        <tr>
          <td>Date de début de location</td>
          <td><%= booking.check_in %></td>
        </tr>
        <tr>
          <td>Date de fin de location</td>
          <td><%= booking.check_out %></td>
        </tr>
        <tr>
          <td>Adresse email de l'utilisateur</td>
          <td><%= booking.user.email %></td>
        </tr>
        <tr>
          <td>Lien vers le profil de l'utilisateur</td>
          <td>
            <button href="#modale<%=booking.user.id%>" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modale<%=booking.user.id%>">
              Voir
            </button>
          </td>
        </tr>
      </table>
    </div>

  </div>


  <div class="modal fade" id="modale<%=booking.user.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Profil de <%= booking.user.firstname %>&nbsp;<%= booking.user.lastname %></h4>
        </div>
        <div class="modal-body">
          <ul class="unstyled">
            <li>Aeroclub: <%= booking.user.aeroclub %></li>
            <li>Heures de vol: <%= booking.user.flight_hours %></li>
            <li>Présentation: <%= booking.user.description %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>


<% end %>

app/views/profiles/bookings/index.html.erb
<div class="container padded">
  <% @bookings.each do |bookings| %>
    <% bookings.each do |booking| %>
      <%= render 'booking_profile', booking: booking %>
    <% end %>
  <% end %>
</div>

app/views/profiles/bookings/pending.html.erb
<div class="container padded">
  <%= render 'user_booking', bookings: @bookings %>
</div>

<% content_for :after_js do %>

  <script>
    $(document).ready(function() {
      $("[name='status-checkbox']").bootstrapSwitch();
      $.fn.bootstrapSwitch.defaults.onColor = 'success';
      $.fn.bootstrapSwitch.defaults.state = 'false';
    })
    $.fn.bootstrapSwitch.defaults.size = 'large';
    $.fn.bootstrapSwitch.defaults.labelText = 'Changer';
    $.fn.bootstrapSwitch.defaults.onText = 'Acceptée';
    $.fn.bootstrapSwitch.defaults.offText = 'Refusée';
    $.fn.bootstrapSwitch.defaults.onColor = 'success';
    $.fn.bootstrapSwitch.defaults.offColor = 'danger';
  </script>
<% end %>